START #1
{}
test
{'type': 'string'}

START #2
2.0
2.0 is not of type 'integer'

Failed validating 'type' in schema:
    {'type': 'integer'}

On instance:
    2.0

START #3
3.0 is not of type 'integer'

Failed validating 'type' in schema['properties']['a']:
    {'type': 'integer'}

On instance['a']:
    3.0
{'a': 3.0}
{'type': 'object', 'properties': {'a': {'type': 'integer'}}}

START #4
{'b': 12}
'test string' is not of type 'integer'

Failed validating 'type' in schema['properties']['b']:
    {'type': 'integer'}

On instance['b']:
    'test string'

START #5
VALUE:  [1, 2]
{'type': 'array', 'storage': 'plain', 'items': {'type': 'integer'}}
3.0 is not of type 'integer'

Failed validating 'type' in schema['items']:
    {'type': 'integer'}

On instance[2]:
    3.0

START #6
VALUE:  [1, 2]

************************************************************************
*  Silk validation error
************************************************************************
Traceback (most recent call last):
  File "/seamless/seamless/silk/validation/validators.py", line 232, in validator_validators
    validator_func(silkobject)
  File "Silk validator 1", line 2, in v
    assert self > 0
AssertionError
************************************************************************


Failed validating 'validators' in schema['items']:
    {'type': 'integer',
     'validators': [{'code': 'def v(self): \n    assert self > 0\n',
                     'language': 'python'}]}

On instance[3]:
    0
